//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KasperskyUITestingProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KasperskyUITestingProject.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all_cs.
        /// </summary>
        internal static string allProductsBtn {
            get {
                return ResourceManager.GetString("allProductsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.kaspersky.ru/antivirus.
        /// </summary>
        internal static string antivirusPageUrl {
            get {
                return ResourceManager.GetString("antivirusPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@class=&apos;AccesibilityButton_button__rj_ej PageHeader_globeWrapper__j_gu0&apos;].
        /// </summary>
        internal static string changeLanguageBtnXpath {
            get {
                return ResourceManager.GetString("changeLanguageBtnXpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@class=&apos;Toggle_item__Qh2Jp Toggle_active__EbOLk MastheadHome_active__2j6Ca&apos;].
        /// </summary>
        internal static string changeToggleForBusinessBtnXPath {
            get {
                return ResourceManager.GetString("changeToggleForBusinessBtnXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откройте продукт «Лаборатории Касперского» одним из перечисленных способов.
        ///Нажмите значок в правом нижнем углу на панели задач или стрелку, чтобы показать скрытые значки..
        /// </summary>
        internal static string firstGuidePicTxt {
            get {
                return ResourceManager.GetString("firstGuidePicTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В разделе «Лицензирование»:
        ///Нажмите  в окне с информацией о лицензии, чтобы скопировать ключ лицензии.
        ///Введите ключ вашей лицензии в поле вверху этой страницы, чтобы активировать продление..
        /// </summary>
        internal static string fourthGuidPicTxt {
            get {
                return ResourceManager.GetString("fourthGuidPicTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@href=&apos;/antivirus&apos; and @data-at-selector=&apos;learn-more-button&apos;]/span/span.
        /// </summary>
        internal static string goToAntivirusPageBtnXPath {
            get {
                return ResourceManager.GetString("goToAntivirusPageBtnXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@href=&apos;/internet-security&apos; and @data-at-selector=&apos;learn-more-button&apos;].
        /// </summary>
        internal static string goToInternetSecurityPageBtnXPath {
            get {
                return ResourceManager.GetString("goToInternetSecurityPageBtnXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@href=&apos;/total-security&apos; and @data-at-selector=&apos;learn-more-button&apos;].
        /// </summary>
        internal static string goToTotalSecurityPageBtnXPath {
            get {
                return ResourceManager.GetString("goToTotalSecurityPageBtnXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@data-index=&apos;0&apos;].
        /// </summary>
        internal static string guideTxtXPath {
            get {
                return ResourceManager.GetString("guideTxtXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@class=&apos;Common_inner__L6GF1 DarkGreenButton_inner__epUUq Common_expandedPadding__e9bdv&apos;].
        /// </summary>
        internal static string HomeSecurityGreenBtnXpath {
            get {
                return ResourceManager.GetString("HomeSecurityGreenBtnXpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.kaspersky.ru/home-security.
        /// </summary>
        internal static string homeSecurityUrl {
            get {
                return ResourceManager.GetString("homeSecurityUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;input-35&apos;].
        /// </summary>
        internal static string inputKeyXPath {
            get {
                return ResourceManager.GetString("inputKeyXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.kaspersky.ru/internet-security.
        /// </summary>
        internal static string internetSecurityPageUrl {
            get {
                return ResourceManager.GetString("internetSecurityPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.kaspersky.ru/.
        /// </summary>
        internal static string KasperskyURL {
            get {
                return ResourceManager.GetString("KasperskyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //h1.
        /// </summary>
        internal static string mainPageTitleXPath {
            get {
                return ResourceManager.GetString("mainPageTitleXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to android_cs.
        /// </summary>
        internal static string productsForAndroid {
            get {
                return ResourceManager.GetString("productsForAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iphone_and_ipad_cs.
        /// </summary>
        internal static string productsForApple {
            get {
                return ResourceManager.GetString("productsForApple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to macos_cs.
        /// </summary>
        internal static string productsForMac {
            get {
                return ResourceManager.GetString("productsForMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to windows_cs.
        /// </summary>
        internal static string productsForWin {
            get {
                return ResourceManager.GetString("productsForWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.kaspersky.ru/renewal-center/home.
        /// </summary>
        internal static string renewalUrl {
            get {
                return ResourceManager.GetString("renewalUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@class=&apos;Common_inner__L6GF1 BlackButtonSecondary_inner___YsFX Common_expandedPadding__e9bdv&apos;].
        /// </summary>
        internal static string RenewalWhiteBtnXPath {
            get {
                return ResourceManager.GetString("RenewalWhiteBtnXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейдите в раздел «Лицензирование» вашего продукта
        ///Выберите пункт Лицензия: осталось X дн., если ваша лицензия еще действительна.
        ///Выберите пункт Лицензия: срок действия истек, если срок вашей лицензии истек..
        /// </summary>
        internal static string secondGuidPicTxt {
            get {
                return ResourceManager.GetString("secondGuidPicTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #__next &gt; div &gt; div &gt; div &gt; main &gt; div:nth-child(4) &gt; div:nth-child(1) &gt; section &gt; div &gt; div &gt; div.MastheadLRC_lrcBlockWrapper__A_nZF &gt; div &gt; div.FormBlock_formWrapper__19PYY &gt; form &gt; button &gt; span &gt; span.
        /// </summary>
        internal static string submitKeyBtnCss {
            get {
                return ResourceManager.GetString("submitKeyBtnCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В разделе «Лицензирование»:
        ///Выберите Информация о лицензии или Подробнее
        ///(Название ссылки зависит от продукта).
        ///Появится окно с подробной информацией о лицензии..
        /// </summary>
        internal static string thirdGuidPicTxt {
            get {
                return ResourceManager.GetString("thirdGuidPicTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop safely online – and save big!.
        /// </summary>
        internal static string titleEnglish {
            get {
                return ResourceManager.GetString("titleEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передовая кибербезопасность для любой компании.
        /// </summary>
        internal static string titleMainPageBusiness {
            get {
                return ResourceManager.GetString("titleMainPageBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлайн-защита, доступная всем.
        /// </summary>
        internal static string titleMainPageHomeSecurity {
            get {
                return ResourceManager.GetString("titleMainPageHomeSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.kaspersky.ru/total-security.
        /// </summary>
        internal static string totalSecurityPageUrl {
            get {
                return ResourceManager.GetString("totalSecurityPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@class=&apos;SliderArrow_sliderArrow__nULnq LightSliderArrow_sliderArrow__JsS_Z LRCLicenseKeyFinder_arrow__hsLPf LRCLicenseKeyFinder_prev__LU1tY SliderArrow_isPrev__JUVXl&apos;].
        /// </summary>
        internal static string ToTheLeftBtnXPath {
            get {
                return ResourceManager.GetString("ToTheLeftBtnXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@class=&apos;SliderArrow_sliderArrow__nULnq LightSliderArrow_sliderArrow__JsS_Z LRCLicenseKeyFinder_arrow__hsLPf LRCLicenseKeyFinder_next__Hjo_b&apos;].
        /// </summary>
        internal static string ToTheRightBtnXPath {
            get {
                return ResourceManager.GetString("ToTheRightBtnXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@href=&apos;https://usa.kaspersky.com/?ignoreredirects=true&apos; and text()=&apos;United States&apos;].
        /// </summary>
        internal static string unitedStatesBtnXpath {
            get {
                return ResourceManager.GetString("unitedStatesBtnXpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key.
        /// </summary>
        internal static string wrongKey {
            get {
                return ResourceManager.GetString("wrongKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то пошло не так. Введите ключ лицензии, указанный в окне лицензирования вашего продукта..
        /// </summary>
        internal static string wrongKeyErrorMessage {
            get {
                return ResourceManager.GetString("wrongKeyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[@id=&apos;label-36&apos;].
        /// </summary>
        internal static string wrongKeyErrorMessageXPath {
            get {
                return ResourceManager.GetString("wrongKeyErrorMessageXPath", resourceCulture);
            }
        }
    }
}
